# Generated by Django 3.0 on 2020-02-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QCMPossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QCMQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QCMUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ManyToManyField(to='QCM.QCMPossibleAnswer')),
            ],
        ),
        migrations.AddField(
            model_name='qcmpossibleanswer',
            name='qcm_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QCM.QCMQuestion'),
        ),
    ]
