# Generated by Django 2.2 on 2020-02-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QCM', '0002_qcmuseranswer_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcmuseranswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QCM.QCMQuestion'),
        ),
    ]
