# Generated by Django 2.2 on 2020-02-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QCM', '0003_auto_20200211_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcmuseranswer',
            old_name='exam',
            new_name='qcm_question',
        ),
    ]
