# Generated by Django 3.0 on 2020-02-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QCM', '0005_auto_20200211_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcmuseranswer',
            name='qcm_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QCM.QCMQuestion'),
        ),
    ]
